<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Визитка магазина</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            background-image: url('https://on-desktop.com/wps/Backgrounds_Wallpaper_with_ornament_035516_.jpg'); /* Путь к изображению фона */
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            text-align: center;
            background-color: rgba(0, 0, 0, 0.7); /* Прозрачный черный фон контейнера */
        }

        h1 {
            color: #f9ff00; /* Цвет заголовка */
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 10px;
            background-color: #f9ff00; /* Цвет кнопки */
            color: #000000; /* Цвет текста кнопки */
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .button:hover {
            background-color: #c2d1aa; /* Цвет кнопки при наведении */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Royal Shop</h1> 
        <a href="https://t.me/+5aIa6Q6PqX4xYjQy" class="button">Новости</a>
        <a href="https://royalshop.brut.store/" class="button">Наш Сайт</a>
        <a href="https://t.me/+5aIa6Q6PqX4xYjQy" class="button">Телеграм</a>
        <a href="https://rutor-24x7.com/threads/royal-shop-torgovaja-vetka-rostov-na-donu-i-oblast-obschenie-mini-opt-i-roznica-mnogo-natura-rabota-ot-1300r-za1gr.122885/page-329#post-11181001" class="button">RuTor</a>
        <a href="https://t.me/royalshopADM" class="button">Работа</a>
    </div>
</body>
</html>
